trabajo/app-trabajo/config/routes.rb
Rails.application.routes.draw do

  resources :courses, :except => [:show]  do
    member do
      get :summary
    end
    resources :exams, :except => [:show] do
      member do
        get :results
        post :results, to: "exams#change_results"
      end
    end
    resources :students, :except => [:show]
  end

  devise_for :users
  
  root :to => "courses#index"
  
end

trabajo/app-trabajo/app/models/student.rb
class Student < ApplicationRecord
  has_many :results, :dependent => :restrict_with_error
  belongs_to :course
  
  validates_presence_of :surname, :name, :dni, :number, :email
  validates_format_of :email, :with =>/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates_format_of :surname, :name, :with =>/\A(?:[-a-z']+|[-a-z']+\s[-a-z']*\s?[-a-z']+)\z/i 
  validates :dni, length: { in: 7..8 }

  validates_numericality_of :dni, :number, :only_integer => true,
    :greater_than_or_equal_to => 1

  validates :dni, :number, :email, :uniqueness => {:scope => [:course_id]}
  validates :name, :uniqueness => {:scope => [:course_id, :surname], message: "should be different, at least. There is someone in this course with that name and surname." }
  
  def to_s
    "#{surname}, #{name}"
  end

  def attended_to? exam
    !(Result.find_by_assoc(self, exam).empty?)
  end

  def score_for exam
   (Result.find_by_assoc self, exam).first
  end

  def surname_with_name
    "#{surname}, #{name}"
  end
end

trabajo/app-trabajo/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_students
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET courses/1/students
  def index
    @students = @course.students.order(:surname, :name)
  end

  # GET courses/1/students/new
  def new
    @student = @course.students.build
  end

  # GET courses/1/students/1/edit
  def edit
  end

  # POST courses/1/students
  def create
    @student = @course.students.build(student_params)

    if @student.save
      redirect_to( course_students_url(@student.course), notice: 'Student was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT courses/1/students/1
  def update
    if @student.update_attributes(student_params)
      redirect_to( course_students_url(@student.course), notice: 'Student was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE courses/1/students/1
  def destroy
    @student.destroy
    if (!@student.results.empty?)
      respond_to do |format|
        format.html { redirect_to course_students_url(@course), alert: 'Student was not destroyed due to the fact it has results related.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to course_students_url(@course), notice: 'Student was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_students
      @course = Course.find(params[:course_id])
    end

    def set_student
      @student = @course.students.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:surname, :name, :number, :dni, :email)
    end
end

trabajo/app-trabajo/app/helpers/students_helper.rb
module StudentsHelper
end

trabajo/app-trabajo/app/views/students/_form.html.erb
<%= form_for([@student.course, @student]) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h6>Oops! <%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h6>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname,class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name,class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number,class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :dni %><br />
    <%= f.number_field :dni,class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email,class:"form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: 'btn btn-outline-warning'%>
    <%= link_to 'Back',  course_students_path(@student.course), class: 'btn btn-outline-dark' %>   
  </div>
<% end %>

trabajo/app-trabajo/app/views/students/edit.html.erb
<div class="container col-md-4 col-md-offset-4" style="width:400px">

  <div class="card" style="width:400px">
    <%=image_tag("course1.jpeg", alt: "Card image, exam", class: "card-img-top")%>
    <div class="card-body">
      <h4 class="card-title">Editing Student</h4>
      <p class="card-text">
        <%= render 'form' %>
      </p>
    </div>
  </div>

</div>

trabajo/app-trabajo/app/views/students/index.html.erb
<div class="container col-md-10 col-md-offset-1 ">
  <h1>Listing <%= @course.year %> Students</h1>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Surname</th>
        <th>Name</th>
        <th>Number</th>
        <th>Dni</th>
        <th>Email</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.surname %></td>
          <td><%= student.name %></td>
          <td><%= student.number %></td>
          <td><%= student.dni %></td>
          <td><%= student.email %></td>
          <td>
            <%= link_to 'Edit', edit_course_student_path(student.course, student), class: 'btn btn-outline-success'  %>
            <%= link_to 'Destroy', [student.course, student],  data: { confirm: 'Are you sure?' }, :method => :delete , class: 'btn btn-outline-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Student', new_course_student_path(params[:course_id]), class: 'btn btn-outline-warning' %>
  <%= link_to 'Back to Courses', courses_path, class: 'btn btn-outline-dark' %>
</div>

trabajo/app-trabajo/app/views/students/new.html.erb
<div class="container col-md-4 col-md-offset-4" style="width:400px">

  <div class="card" style="width:400px">
    <%=image_tag("course1.jpeg", alt: "Card image, student", class: "card-img-top")%>
    <div class="card-body">
      <h4 class="card-title">New Student</h4>
      <p class="card-text">
        <%= render 'form' %>
      </p>
    </div>
  </div>

</div>