p5/practica_cinco/config/routes.rb
Rails.application.routes.draw do

  resources :offices
  resources :employees
  get 'polite/salute'

  root 'polite#salute'
end

p5/practica_cinco/app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :office

    validates :name, presence: true, length: { in: 1..150 }
    validates :e_number, presence: true, uniqueness: true

end

p5/practica_cinco/app/models/office.rb
class Office < ApplicationRecord
    has_many :employees

    scope :vacant, -> { where(office: nil) }
    scope :occupied, -> { where.not(office: nil) }

    validates :name, presence: true, length: { in: 1..255 }
    validates :available, exclusion: { in: [nil] }

    # validamos que el numero sea uno valido para arg
    validates :phone_number, presence: true, length: { in: 1..30 }, 
    format: { with: /(\(?\d{3}\)?[- .]?\d{4}[- .]?\d\d\d\d)|(\(?\d{4}\)?[- .]?\d{3}[- .]?\d\d\d\d)|(\(?\d{5}\)?[- .]?\d{2}[- .]?\d\d\d\d)/}
    

    
end

p5/practica_cinco/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :set_locale
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  
end

p5/practica_cinco/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.fetch(:employee, {})
    end
end

p5/practica_cinco/app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_offiz, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @offiz = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @offiz = Office.new(offiz_params)

    respond_to do |format|
      if @offiz.save
        format.html { redirect_to @offiz, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @offiz }
      else
        format.html { render :new }
        format.json { render json: @offiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @offiz.update(offiz_params)
        format.html { redirect_to @offiz, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @offiz }
      else
        format.html { render :edit }
        format.json { render json: @offiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @offiz.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offiz
      @offiz = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offiz_params
      params.fetch(:offiz, {})
    end
end

p5/practica_cinco/app/controllers/polite_controller.rb
class PoliteController < ApplicationController
  
  # cuando hacemos http://localhost:3000/polite/salute vemos un saludo random
  def salute
    @hi = ['hello_sir', 'hello_madam', 'hi'].shuffle.first
  end
end

p5/practica_cinco/app/helpers/employees_helper.rb
module EmployeesHelper
end

p5/practica_cinco/app/helpers/offices_helper.rb
module OfficesHelper
end

p5/practica_cinco/app/helpers/polite_helper.rb
module PoliteHelper
end

p5/practica_cinco/app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

p5/practica_cinco/app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

p5/practica_cinco/app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

p5/practica_cinco/app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

p5/practica_cinco/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

p5/practica_cinco/app/views/offices/_form.html.erb
<%= form_with(model: offiz, local: true) do |form| %>
  <% if offiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offiz.errors.count, "error") %> prohibited this offiz from being saved:</h2>

      <ul>
      <% offiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

p5/practica_cinco/app/views/offices/edit.html.erb
<h1>Editing Offiz</h1>

<%= render 'form', offiz: @offiz %>

<%= link_to 'Show', @offiz %> |
<%= link_to 'Back', offices_path %>

p5/practica_cinco/app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |offiz| %>
      <tr>
        <td><%= link_to 'Show', offiz %></td>
        <td><%= link_to 'Edit', edit_offiz_path(offiz) %></td>
        <td><%= link_to 'Destroy', offiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offiz', new_offiz_path %>

p5/practica_cinco/app/views/offices/new.html.erb
<h1>New Offiz</h1>

<%= render 'form', offiz: @offiz %>

<%= link_to 'Back', offices_path %>

p5/practica_cinco/app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_offiz_path(@offiz) %> |
<%= link_to 'Back', offices_path %>

p5/practica_cinco/app/views/polite/salute.html.erb
<h1>Polite#salute</h1>
<%= t @hi %>